#
# Maintenance macOS
#
---
- hosts: all
  serial: '{{ servar | default(1) }}'
  gather_facts: no
  vars_files:
    - vars/defaults.yml
  tasks:
    - import_tasks: tasks/parallels-start.yml
      when: prl_id is defined

    - import_tasks: tasks/macports-bootstrap.yml

    - name: Gather facts
      gather_facts:

    - import_tasks: tasks/install-ssh-keys.yml

    - import_tasks: tasks/setup-hostname.yml

    - import_tasks: tasks/install-updates.yml
      when: skip_updates is not defined

    - import_tasks: tasks/macports.yml

    - import_tasks: tasks/cleanup-disk.yml
      when: prl_id is defined and skip_cleanup_disk is not defined

    - import_tasks: tasks/shrink-disk.yml
      when: prl_id is defined and skip_shrink_disk is not defined

    - import_tasks: tasks/parallels-shutdown.yml
      when: prl_id is defined

    - name: Make a clean snapshot
      local_action: command prlctl snapshot {{ prl_id }} -n '{{ snapshot_name }}' -d 'MacPorts {{ version }}'
      when: prl_id is defined
