#
# Maintenance macOS
#
---
- hosts: all
  serial: '{{ servar | default(1) }}'
  gather_facts: no
  vars_files:
    - vars/defaults.yml
  tasks:
    - import_tasks: tasks/parallels-start.yml
      when: prl_id is defined

    - import_tasks: tasks/macports-bootstrap.yml
      when: (bootstrap_python is defined) or (bootstrap_curl is defined)

    - name: Remove bootstrap MacPorts
      become: yes
      file:
        state: absent
        path: '{{ bootstrap_prefix }}'
      when: (bootstrap_python is not defined) and (bootstrap_curl is not defined)

    - name: Gather facts
      gather_facts:

    - import_tasks: tasks/install-ssh-keys.yml

    - import_tasks: tasks/setup-hostname.yml

    - import_tasks: tasks/parallels-install-tools.yml
      when: (prl_id is defined) and (skip_parallels_tools is not defined)

    - import_tasks: tasks/install-updates.yml
      when: skip_updates is not defined

    - import_tasks: tasks/macports.yml

    - import_tasks: tasks/cleanup-disk.yml
      when: (prl_id is defined) and (skip_cleanup_disk is not defined)

    - import_tasks: tasks/shrink-disk.yml
      when: (prl_id is defined) and (skip_shrink_disk is not defined)

    # shrink requires a lot of time and Parallels Tools my produces a lot of logs
    # clean it second time
    - import_tasks: tasks/cleanup-disk.yml
      when: (prl_id is defined) and (skip_cleanup_disk is not defined) and (skip_shrink_disk is not defined)

    - import_tasks: tasks/parallels-shutdown.yml
      when: prl_id is defined

    - name: Make a clean snapshot
      local_action: command prlctl snapshot {{ prl_id }} -n '{{ snapshot_name }}' -d 'MacPorts {{ version }}'
      when: prl_id is defined
