#
# Maintenance macOS
#
---
- hosts: all
  serial: '{{ servar | default(1) }}'
  gather_facts: no
  vars_files:
    - vars/defaults.yml
  tasks:
    - import_tasks: tasks/parallels-start.yml
      when: prl_id is defined

    - import_tasks: tasks/macports-bootstrap.yml
      when: (bootstrap_python is defined) or ('bootstrap_curl' in group_names)

    - name: Remove bootstrap MacPorts
      become: yes
      file:
        state: absent
        path: '{{ bootstrap_prefix }}'
      when: (bootstrap_python is not defined) and ('bootstrap_curl' not in group_names)

    - name: Gather facts
      gather_facts:

    - import_tasks: tasks/install-ssh-keys.yml

    - import_tasks: tasks/setup-hostname.yml

    - import_tasks: tasks/parallels-install-tools.yml
      when: (prl_id is defined) and (skip_parallels_tools is not defined)

    - import_tasks: tasks/install-updates.yml
      when: skip_updates is not defined

    - import_tasks: tasks/macports.yml

    - import_tasks: tasks/cleanup-disk.yml
      when: skip_cleanup_disk is not defined

    - import_tasks: tasks/parallels-shutdown.yml
      when: prl_id is defined

    - name: Make a maintenance snapshot
      local_action: command prlctl snapshot {{ prl_id }} -n 'Maintenance' -d 'MacPorts {{ version }}'
      when: prl_id is defined

    # simple confirm that it still can start :)
    - import_tasks: tasks/parallels-start.yml
      when: prl_id is defined

    - import_tasks: tasks/parallels-shutdown.yml
      when: prl_id is defined
