#
# Start a Parallels VM
#
---
- name: Start a machine
  local_action: command prlctl start {{ prl_id }}
  ignore_errors: yes

- name: Wait for connection
  vars:
    ansible_ssh_retries: 60
    ansible_ssh_timeout: 10
  raw: whoami
