#
# Shrink disk size on macOS.
#
---
- name: Enable apfs defragment on /
  become: yes
  shell: 'diskutil apfs defragment / enable'
  ignore_errors: yes

- name: Enable apfs defragment on /Volumes/Macintosh HD
  become: yes
  shell: 'diskutil apfs defragment /Volumes/Macintosh\ HD enable'
  ignore_errors: yes

- name: Enable apfs defragment on /System/Volumes/Data
  become: yes
  shell: 'diskutil apfs defragment /System/Volumes/Data enable'
  ignore_errors: yes

- name: Shrink disks
  become: yes
  shell: |
    if [ -d {{ item }} ]; then
      dd if=/dev/zero of={{ item }}/zero.file bs=1048576 || true
      cat /dev/zero > {{ item }}/zero.small.file || true
      sync
      sleep 1
      sync
      rm -f {{ item }}/zero.small.file
      rm -f {{ item }}/zero.file
    fi
  ignore_errors: yes
  with_items:
    - '/'
    - '/Volumes/Macintosh\ HD'
    - '/System/Volumes/Data'
